### ISSUE TITLE
Problema con funzione Override

### ISSUE THREAD

**Issue by niky1989** [madchicken/homebridge-comelit-icona#1]
Il plugin funziona correttamente, nel caso in cui si personalizzi con la funzione "override" una serratura/portone si va a creare un doppio comando per la stessa serratura, quella di default più quella dell'override, entrambe funzionano correttamente. E' normale?
Il problema è risolvibile separando i due accessori tramite homekit (mostra in riquadri separati) e nascondendo il comando di default. 
![Schermata 2022-04-23 alle 11 48 37](https://user-images.githubusercontent.com/88239769/164889820-37b16173-d693-4c48-b6fd-32eb7f2c512b.png)
![IMG_7412](https://user-images.githubusercontent.com/88239769/164889989-7bed6df7-3727-479f-aa8e-4bd9d7d80b43.PNG)

**Comment by madchicken** [comment]
I'll check this out

**Comment by madchicken** [comment]
Sorry, with overrides you mean the door type config?

<img width="713" alt="Screenshot 2022-10-21 at 18 40 47" src="https://user-images.githubusercontent.com/296618/197246852-b00a2215-93f6-4e8d-b62f-49c3125ae751.png">

**Comment by madchicken** [comment]
Also, could you please copy here your JSON configuration?

**Comment by Snoopy5570** [comment]
Ho un Portone con comando di sola apertura, ma ho lo stesso problema, mi vengono abilitare due icone, quella temporizzata a me non funziona neanche.
![D467EE75-7BD2-4907-8E57-272C4E384B61](https://user-images.githubusercontent.com/67944815/202389235-e221a2bf-65de-4c1e-b881-91032be6abeb.jpeg)
![79AB76F6-C51F-466A-AE69-5DC0FA7BB5A9](https://user-images.githubusercontent.com/67944815/202389243-6ba508ec-edbc-46b3-be19-bd6a66d2e9ca.jpeg)
![E357CDE2-E7CB-45A5-8690-F5C4AF4EB9AD](https://user-images.githubusercontent.com/67944815/202389247-d3222de3-ca5f-4e0e-ad4b-23107e0220d0.jpeg)

**Comment by madchicken** [comment]
Dall'applicazione ufficiale comelit vedi il portone e riesci ad aprirlo?
Il duplicato probabilmente è dovuto alla cache di homebridge. Prova ad eliminare entrambe gli accessori dalla cache utilizzando l'interfaccia web di homebridge, nella sezione Homebridge Settings/Remove Single Cached Accessory

**Comment by Snoopy5570** [comment]
Grazie Pierpaolo, ho risolto.
Ma per un semplice comando di semplice apertura occorre Stay opened time? É il tempo di aggiornamento stato? Come lo dovrei tenere settato? É un portone condominiale che non può rilevare la chiusura.
Complimenti per il plugin che aspettavo da tanto tempo, mi hai risolto un bel problema.
Grazie mille.

**Comment by madchicken** [comment]
Lo stay opened time serve per reimpostare a "chiuso" il portone dopo un po'. Più che altro è per HomeKit e lo stato da mostrare sull'interfaccia

**Comment by Snoopy5570** [comment]
Quindi dovrei impostare un valore molto basso anche perché forse non potrei ridare comando di apertura finché non lo vede chiuso. Giusto?

**Comment by madchicken** [comment]
Esatto...io ho misurato quanto ci mette circa a richiudersi il portone per esempio.
