### ISSUE TITLE
homebridge non vede più accessorio comelit

### ISSUE THREAD

**Issue by Snoopy5570** [madchicken/homebridge-comelit-icona#10]
Salve, ho visto che su HomeKit il portone non riceveva piu' comandi tramite Homebridge.
ho provato a cancellare la cache del singolo accessorio su homebridge, disinstallare e reinstallare il plugin Icona... ma nulla.
Homebridge non riconosce più' l'accessorio anzi restituisce questo errore:
[07/10/2023, 08:57:32] [Icona] connected
[07/10/2023, 08:57:32] [Icona] Received code 404 from ICONA client during authentication phase. Shutting down.

Potete darmi aiuto? ho ricontrollato tutto anche il token.
Grazie

**Comment by Snoopy5570** [comment]
Conoscete da cosa dipende questo messaggio???
Received code 404 from ICONA client during authentication phase. Shutting down.

**Comment by Snoopy5570** [comment]
Problema risolto… effettuato Reset Factory Default sul videocitofono, reinserito il nuovo token.

**Comment by madchicken** [comment]
Scusa @Snoopy5570 ma non ho ricevuto le notifiche di questi messaggi e quindi non ho risposto...
